# Generated by Django 2.1 on 2018-10-01 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='livro',
            name='avaliacaoNegativa',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='livro',
            name='avaliacaoPositiva',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
