# Generated by Django 2.1 on 2018-10-01 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0002_auto_20181001_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livro',
            name='avaliacaoNegativa',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='livro',
            name='avaliacaoPositiva',
            field=models.IntegerField(null=True),
        ),
    ]
